Fix incorrect graph rendering
Jenkins uses JFreeChart library to render different graphs
However this library requires `-Djava.awt.headless=true` JVM option to correctly
render graphs. Otherwise library initialization fails with exception
```
java.lang.NoClassDefFoundError: Could not initialize class org.jfree.chart.JFreeChart
```

Also this requires to use default jenkins image (not slim one) otherwise
graphs doesn't work either.